### ISSUE TITLE
Some problems about environment

### ISSUE THREAD

**Issue by Superman-Valencia** [mogwai/nanodrz#3]
Excuse me, when I ran the code, the following situation occurred. 
<img width="338" alt="image" src="https://github.com/mogwai/nanodrz/assets/70886521/4a23eca5-7d41-4588-9c58-f4d4c4f84447">
I tried various versions of dac, but still couldn't solve it. 
Did you encounter similar problems and how did you solve them?

**Comment by mogwai** [comment]
I've just fixed main so that you don't need to have dac installed anymore.

**Comment by Superman-Valencia** [comment]
> I've just fixed main so that you don't need to have dac installed anymore.

Thank you very much!
